### ISSUE TITLE
[Bug] Not able to break Smooth Stone Tiles and get the block back

### ISSUE THREAD

**Issue by IamWill-C** [SuperMartijn642/Rechiseled#101]
**Version Info**
- Minecraft, 1.21.1
- Rechiseled, rechiseled-1.1.6-forge-mc1.21
- Fusion, fusion-1.1.1-forge-mc1.21

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt

**Description of the Bug**
So far, I have only found that Smooth Stone Tiles with connected textures (does this regardless of whether or not connected textures are on) do not break with a pickaxe & you do not receive the block back after breaking
This might be the case with all stone variant blocks from Rechiseled, tried with a few others and got the same result

**Steps to Reproduce**
Use the chisel to change Stone to Smooth Stone Tiles with connected textures on, place Smooth Stone Tiles, and try to mine the block

**Screenshots**
N/A, also video files are too big to attach

**Comment by IamWill-C** [comment]
Forgot to specify that I'm using Forge Modloader

**Comment by SuperMartijn642** [comment]
This has been fixed in Rechiseled 1.1.6a for Minecraft 1.21 & 1.21.1.
Thank you for reporting the issue!
