### ISSUE TITLE
[Bug] mod not working

### ISSUE THREAD

**Issue by vivyllane** [SuperMartijn642/Rechiseled#102]
**Version Info**
- Minecraft, 1.21.1
- Rechiseled, 1.1.6
- Fusion, ...

**What mod loader are you using?**: Fabric

**Description of the Bug**
the mod shows up in the mod menu(s) like normal, but none of it's features show up in-game.

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
What exactly does not show up in game, what are you expecting to see where but isn't there?
Also, are you playing on a server and if so, did you also install the mod on the server?

**Comment by vivyllane** [comment]
sorry, shouldve been clearer. specifically, i just cannot make the chisel. i haven't checked the creative menu to see if it exists otherwise, but the recipe you showed on the mod page just isnt working. and no, i am not playing on a server.thank you!
-------- Original message --------From: Martijn van den Brand ***@***.***> Date: 8/22/24  1:10 AM  (GMT-07:00) To: SuperMartijn642/Rechiseled ***@***.***> Cc: vivyllane ***@***.***>, Author ***@***.***> Subject: Re: [SuperMartijn642/Rechiseled] [Bug] mod not working (Issue #102) 
What exactly does not show up in game, what are you expecting to see where but isn't there?
Also, are you playing on a server and if so, did you also install the mod on the server?

**Comment by SuperMartijn642** [comment]
Ah that has just been fixed in Rechiseled version 1.1.6a then, so should work after updating.
Thank you for reporting the issue!

**Comment by vivyllane** [comment]
oh i just saw you fixed it already! thank you so much! have a good day :)
-------- Original message --------From: mijashdi ***@***.***> Date: 8/22/24  3:49 PM  (GMT-07:00) To: SuperMartijn642/Rechiseled ***@***.***> Subject: Re: [SuperMartijn642/Rechiseled] [Bug] mod not working (Issue #102) sorry, shouldve been clearer. specifically, i just cannot make the chisel. i haven't checked the creative menu to see if it exists otherwise, but the recipe you showed on the mod page just isnt working. and no, i am not playing on a server.thank you!-------- Original message --------From: Martijn van den Brand ***@***.***> Date: 8/22/24  1:10 AM  (GMT-07:00) To: SuperMartijn642/Rechiseled ***@***.***> Cc: vivyllane ***@***.***>, Author ***@***.***> Subject: Re: [SuperMartijn642/Rechiseled] [Bug] mod not working (Issue #102) 
What exactly does not show up in game, what are you expecting to see where but isn't there?
Also, are you playing on a server and if so, did you also install the mod on the server?
