### ISSUE TITLE
[Question] breaking speed

### ISSUE THREAD

**Issue by vivyllane** [SuperMartijn642/Rechiseled#104]
**Question**
is the speed of breaking chiseled blocks supposed to be the same across all tools? any tool i use breaks it at the same speed as when i break it while holding nothing.

**Comment by SuperMartijn642** [comment]
I have fixed the missing mining tags for Minecraft 1.21 & 1.21.1. Please use the bug template, so I have the info I need such as modloader and Minecraft version.
I assume you were using Minecraft 1.21 or 1.21.1, so the issue should be fixed now. If not, feel free to create a new issue with the appropriate info.
Anyways, thank you for reporting the issue!
