### ISSUE TITLE
[Bug] Blocks don't show on Dynmap

### ISSUE THREAD

**Issue by crudelis** [SuperMartijn642/Rechiseled#11]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, rechiseled-1.0.10a-mc1.18
- dynmap,  Dynmap-3.4-beta-4-forge-1.18.2
- dynmapBlockScan, DynmapBlockScan-3.4-beta-4-forge-1.18

**Description of the Bug**
ReChiseled is not rendered using Dynmap and DynmapBlockScan. The Additional Lanterns made by SuperMartijn642 are well rendered.

**Steps to Reproduce**

**Screenshots**

![chrome_EPm4Wjp5sU](https://user-images.githubusercontent.com/5772379/179543359-fb2f8af4-05b0-4de6-a981-e4adb0afd101.png)
![179543338-1c530575-092c-44cf-aed5-b5158e8ec9ac](https://user-images.githubusercontent.com/5772379/179668623-b232f681-ef3d-4067-b6b8-80788def63f0.png)

**Comment by jahands** [comment]
Experiencing the same thing - I wonder how we could fix this

**Comment by SuperMartijn642** [comment]
Should no longer be relevant now.
Thank you for reporting the issue!
