### ISSUE TITLE
[Bug] 1.18.2 Certain blocks cause a 'creative Inventory' allowing for almost any block to be converted

### ISSUE THREAD

**Issue by Sharktail100** [SuperMartijn642/Rechiseled#111]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, 1.1.6
- Fusion, 1.1.1

**What mod loader are you using?**
Forge - 40.2.10

**Description of the Bug**
Random 'chiselable' blocks put into the Chisel GUI allows for that block to be converted 1:1 to any block (Ex. Andesite -> Birch Doors, Calcite -> Warped Trapdoor). However, blocks with a openable GUI (I.E. Chest, Crafting Table, Anvil, etc), do not seem to be included. I've also noticed that when I hover over 'Chisel All' It allows for open inventory slots and other 'universal' blocks to be chiseled.

**Blocks that I've found to cause this are...**
- Andesite
- Calcite

**Steps to Reproduce**
1. Right Click with chisel in hand
2. Put a block inside the GUI (Shift Click or Click and drag)
3. See every block in Minecraft

**Screenshots**
Calcite
![image](https://github.com/user-attachments/assets/33105c41-4102-45c0-be1f-8a8d180c93b0)

Andesite
![image](https://github.com/user-attachments/assets/ecb8dae9-28a7-4dc8-b2fe-84e7d039b298)

Chisel All
![image](https://github.com/user-attachments/assets/9b0633d8-2b24-4866-9fda-14f54368d00b)

**Comment by SuperMartijn642** [comment]
This is caused by the Rechiseled Chipped integration mod or whatever it is called. Please report the issue to them.
