### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Kr0m4t1c** [SuperMartijn642/Rechiseled#12]
**Version Info**
- Minecraft forge 1.14.4 (28.2.26)
- Rechiseled 1.0.10

**Steps to Reproduce**
move any item into the chisel.

**latest.log**
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/9297364/latest.log)

**Comment by SuperMartijn642** [comment]
I fixed it now in Rechiseled 1.0.10a for Minecraft 1.14.

Thank you for reporting the issue!
