### ISSUE TITLE
[Minor Bug] Breaking Animation uses whole texture map instead of particles?

### ISSUE THREAD

**Issue by 4AC11** [SuperMartijn642/Rechiseled#13]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, ...

**Description of the Bug**

I'm not entirely sure what the exact issue is here, or how vanilla handles it, but it seems like Rechiseled uses WAY more texture for its breaking particles than other blocks - Like I said I'm not entirely sure what it is, but something about it is just super jarring to look at for me

Feel free to ignore this if its not a big enough deal to mess with lol

**Steps to Reproduce**

1) Place any Rechiseled block
2) Left click

**Screenshots**
![image](https://user-images.githubusercontent.com/97819008/192650646-288ecf5e-57b9-4173-be22-000d82d0f960.png)
![image](https://user-images.githubusercontent.com/97819008/192650674-675941b1-69d2-4aca-a1ea-dacb3e3333c7.png)
![image](https://user-images.githubusercontent.com/97819008/192650692-9d4a4a30-ef14-43e0-900c-395d8abe08de.png)

Vanilla and the original Chisel mod for comparison:
![image](https://user-images.githubusercontent.com/97819008/192651171-7421d593-f763-4a9f-baa2-79879cdd56ec.png)
![image](https://user-images.githubusercontent.com/97819008/192651840-4aa73a1d-157b-4636-ad8d-cf914b11d04b.png)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.0 of Rechiseled.
Thank you for reporting the issue!
