### ISSUE TITLE
[Bug] Dupe bug

### ISSUE THREAD

**Issue by PORTB** [SuperMartijn642/Rechiseled#14]
**Version Info**
- Minecraft, 1.19.2 forge 43.1.32
- Rechiseled, rechiseled-1.0.10c-forge-mc1.19

**Description of the Bug**
Chisel can be used to dupe items. This is caused by the chisel stacking for some reason

**Steps to Reproduce**
1. craft a stack of chisels 
2. Put an item into the chisel (e.g. wood planks)
3. close the chisel and split the stack into individual items
4. take items out of all the individual chisels

**Screenshots**
...
![2022-10-01_13 30 41](https://user-images.githubusercontent.com/34615701/193385741-8738ef38-0193-40b7-8a62-e6f77b42a037.png)

![2022-10-01_13 30 57](https://user-images.githubusercontent.com/34615701/193385745-0632a389-fb7c-4cee-a049-4ec6d5740609.png)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.0.11.

Thank you for reporting the issue!
