### ISSUE TITLE
[Feature] Stop bottom to stop the animation

### ISSUE THREAD

**Issue by f0kx** [SuperMartijn642/Rechiseled#15]
Hey,

if there is a stop button in the pre-picture in gui to stop the rotation of the model so you can rotate it by yourself without starting moving by itself to have a better look at it...that would be great 👍 

Have a great day and thx for your mod and hard work.

**Comment by SuperMartijn642** [comment]
I added a button now to toggle whether the preview rotates or not.
It is available in version 1.0.13 of Rechiseled.

Thank you for the suggestion!

**Comment by f0kx** [comment]
wow thank you <3
