### ISSUE TITLE
[Feature] Suggestions for Re-chiseled

### ISSUE THREAD

**Issue by Nevrai** [SuperMartijn642/Rechiseled#16]
I’ve really missed Chisel in newer versions, so I’ve been enjoying [Re-chiseled](https://www.curseforge.com/minecraft/mc-mods/rechiseled) a lot! Here’s just a few suggestions that I think would improve the mod quite a bit. Every feature listed below was part of the original Chisel mod and are the features I think should be implemented the most in Re-chiseled.

1\. Add a button to disable rotating. Personally, the block/blocks rotating in the GUI makes it quite annoying to select blocks, as you have to either wait until they’re rotated to see them or keep rotating them manually every second or two. A simple button to disable the blocks rotating in the chisel GUI would be a simple addition, yet a much appreciated one.

~~2\. Add a “chisel all” button, which chisels all blocks of the same type (has to be the same type of chiselled block—e.g., zag) in your inventory to whatever you selected. Perhaps you could achieve this by holding the sneak key whilst pressing the chisel button like in the original Chisel.~~

3\. Add factory blocks. The factory blocks were one of my favourite blocks in the original Chisel mod. Some of them had animated textures, such as moving fans. I’d also love to see the antiblocks (solid-coloured blocks with no visible hitbox), lavastone blocks, as well as the other unique blocks that Chisel added, but factory blocks were by far my favourite. 1.18.2 and 1.19.2 are pretty lacking in terms of nice industrial-looking blocks.

**Comment by HelloJosephine** [comment]
Was going in here to ask about the rotating of the preview. I get carsick/seasick easily, and I would really appreciate being able to turn it off <3

@DeleteMetaInf If you click the chisel button and not just drag out the stack in the chisel, it does chisel all blocks in your inventory. Or maybe I misunderstood what you are asking for :)

**Comment by wantedkeks** [comment]
Yes, i also support the requests 1 and 3. that would be very glad!

**Comment by SuperMartijn642** [comment]
@wantedkeks 1 has already been added.

As for 3, I am not copying any textures from Chisel and I will likely not be adding factory blocks.
