### ISSUE TITLE
[Feature] Make chisel remember selected block

### ISSUE THREAD

**Issue by milkev** [SuperMartijn642/Rechiseled#18]
**Is your feature request related to a problem? Please describe.**
When creating large quantities of a chiseled block (especially a connecting one) you have to reselect the block (and if its connecting) for every stack you pass through, which can be rather time consuming and annoying to do especially with very large builds.

**Describe the solution you'd like**
Have the chisel remember the connecting option, and what block was selected. atleast during the same gui session, it would just make it easier for mass production.

A couple alternatives;
A rf powered block that can chisel automatically.
A button to chisel all of x block into y block.
Compatability with another mods automation, such as the create mechanical saw.

**Comment by SuperMartijn642** [comment]
> A button to chisel all of x block into y block.

This is what the button next to item slot already does right?

**Comment by milkev** [comment]
oh dang it does, i didnt even realize that was a button. my bad!
