### ISSUE TITLE
[Bug] Stone Variants arnt breakable after last Update

### ISSUE THREAD

**Issue by f0kx** [SuperMartijn642/Rechiseled#19]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.0.11

**Description of the Bug**
The cleanstone variants arnt breakable after update. You need too long to break one block

**Steps to Reproduce**
Take a Vhisel and place a clean stone in it
Form it to another variant (exp: diagonal stone tiles) 
Place it
Break it with pickaxe
its like breaking obsidian

**Screenshots**
![image](https://user-images.githubusercontent.com/14795020/210547538-275bcc9c-ec26-4856-a606-b02430b5bc8b.png)

**Comment by f0kx** [comment]
![image](https://user-images.githubusercontent.com/14795020/210550333-934029cf-a49b-4a84-b6a9-22b6119e6a9f.png)

![image](https://user-images.githubusercontent.com/14795020/210550360-62559d61-b98d-423e-8ef5-25e6a0aff8db.png)

**Comment by f0kx** [comment]
You see both cobblestone typed also have differents stats whats breakable and what isnt

**Comment by SuperMartijn642** [comment]
Seems I made typo when generating the mining tags, so it added the regular variant twice instead of the connecting variant. I fixed it now in version 1.0.12.

Thank you for reporting the issue!
