### ISSUE TITLE
[Bug] Chisel UI Rendering in corner of screen

### ISSUE THREAD

**Issue by nmills3** [SuperMartijn642/Rechiseled#22]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.0.12a

**Description of the Bug**
Chisel UI rendering in the wrong place (top left corner)
This worked fine before updating to chisel 1.0.12a (worked on 1.0.12)

**Steps to Reproduce**
open chisel UI. place block into chisel

**Screenshots**

![image](https://user-images.githubusercontent.com/26787639/216148591-22d3b0d6-626d-40e2-8269-f30cecbb086b.png)

**Comment by SuperMartijn642** [comment]
Have you also updated my core library?

**Comment by nmills3** [comment]
what's the lib called? I assumed curseforge would be smart enough to update the dependencies on it's own

**Comment by SuperMartijn642** [comment]
Just SuperMartijn642's Core Library.
I released updates together for Rechiseled and my core library which moves the translation of those elements from Rechiseled to my core library to avoid some issues with other mods. If only Rechiseled is updated, it thus won't be shifted

**Comment by nmills3** [comment]
that fixed it, thanks. My fault for assuming curseforge would be do it
