### ISSUE TITLE
[Question] Is there any difference between this mod and chisel?

### ISSUE THREAD

**Issue by Jaec0b** [SuperMartijn642/Rechiseled#23]
**Question**
Is there any difference between this mod and chisel?

**Comment by SuperMartijn642** [comment]
Rechiseled uses the same concept as Chisel, i.e. having a chisel item which allows you to swap between many similar textures for a given block.
Apart from this, there's no overlap between the mods. All available blocks and textures in Rechiseled are different from Chisel. Additionally Rechiseled allows you to choose between connected and non-connected textures.
