### ISSUE TITLE
[Crash] 1.19.4 Model Bake Failure

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SuperMartijn642/Rechiseled#25]
**Version Info**
- Minecraft, 1.19.4 Forge 45.0.27
- Rechiseled, rechiseled-1.0.12a-forge-mc1.19.3.jar

**Crash report (~/logs/latest.log)**
Crashlog https://gist.github.com/P3rf3ctXZer0/86702f9b79e728e012e124808ec21079
Latest https://gist.github.com/P3rf3ctXZer0/5aa888d8d1fdbcafc1558a683a9b1e78

**Comment by SuperMartijn642** [comment]
Should also work with the dedicated file for 1.19.4 for now.
Again, thank you for reporting the issue! 🙂
