### ISSUE TITLE
[Bug] fabric launch crash

### ISSUE THREAD

**Issue by lostopkk** [SuperMartijn642/Rechiseled#29]
**Version Info**
- Minecraft, 1.19.4
- Rechiseled, 1.0.12

**Description of the Bug**
when initialize with fabric api, crash

**Steps to Reproduce**
1. download the mod, with the libs

Crash log: https://mclo.gs/acqRF5A

**Comment by SuperMartijn642** [comment]
Should be fixed now.
Thank you for reporting the issue!

**Comment by lostopkk** [comment]
@SuperMartijn642 another crash, reopened issue
crash: https://mclo.gs/pSkwz0B
