### ISSUE TITLE
[Bug] Severe incompatibility with Moonlight Lib causing missing textures

### ISSUE THREAD

**Issue by Flaguna2** [SuperMartijn642/Rechiseled#33]
**Version Info**
- Minecraft, 1.19.4
- Rechiseled, 1.0.13 fabric

**Description of the Bug**
Whenever the game is loaded with Rechiseled and Moonlight Lib, several, and I mean SEVERAL (almost 70%) of the Mod's blocks fail to load their respective textures. Issue seems to cause random blocks to fail to load, changing the blocks at every game startup (see screenshots below)

Removing Moonlight Lib "fixes" the issue.

Additional Modlist (all for Fabric of course):
Cloth Config 10.0.96
Fabric API 0.83.0
Fabric Language Kotlin 1.9.4 + Kotlin 1.8.21
Memory Leak Fix 1.0.0
Modmenu 6.2.2
Moonlight 2.4.16
Rechiseled 1.0.13
supermartijn642 config lib 1.1.6
supermartijn642 core lib 1.1.9a

**Steps to Reproduce**
1. Have Rechiseled and dependecies installed
2. Have Moonlight Lib installed
3. Open the game
4. Look at Rechiseled's blocks tab

**Screenshots**
Game with Moonlight installed
![2023-06-08_02 30 21](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/55e2f2ff-f51b-4b31-b2d1-76317d8e8c70)

Game without Moonlight
![2023-06-08_02 31 18](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/b0cde09b-6614-41d4-848e-fe0bc0954ccc)

Random blocks failing to load (Moonlight installed)
Startup 1
![2023-06-08_02 37 07](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/a891b9d5-2c20-428f-a4ba-d841d3321d38)

Startup 2
![2023-06-08_02 38 29](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/8dc059af-909e-40b5-abab-68cfc45b765b)

Blocks tab preview
![2023-06-08_02 38 45](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/74c7f9bc-1c65-4e28-b0b3-b7a8906f769e)

Also, even without Moonlight, these blocks failed to load properly, although this may also be random, since I didn't test this enough
EDIT: Confirmed random? sometimes it loads all textures, sometimes it doesn't for random blocks.
![2023-06-08_02 32 43](https://github.com/SuperMartijn642/Rechiseled/assets/86506105/37936c2c-8856-40b4-8448-4e0d7e1ca823)

I hope this helps and I hope I'm not being dumb here

**Comment by SuperMartijn642** [comment]
Should be completely fixed now in version 1.1.0 of Rechiseled.
Thank you for reporting the issue!
