### ISSUE TITLE
[Crash] Crash with Create

### ISSUE THREAD

**Issue by AmbroseSilverWolfe** [SuperMartijn642/Rechiseled#34]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, 1.1.0

**Steps to Reproduce**
Have the create mod with latest version of rechiseled on a 1.18.2 game

**Crash report (~/logs/latest.log)**
Can't find the report, but it had to do with create:copper_shingles

I reverted back to the previous version of re-chiseled (and removed Fusion) and it worked fine
This crashed not only my game, it also crashed the server I run on startup

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.0a of Rechiseled.
Thank you for reporting the issue!
