### ISSUE TITLE
[Crash] During launch with Iris

### ISSUE THREAD

**Issue by TheFurryDevil** [SuperMartijn642/Rechiseled#35]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.1.0

**Steps to Reproduce**
- Install Rechiseled and dependencies
- Install Iris and dependencies
- Launch the game

**Crash report (~/logs/latest.log)**
[latest.log](https://pastebin.com/cSJ2UqS0)
This log was made with Iris 1.4.5, because 1.6.4 (and 1.6.2) did not produce anything aside from a JRE dump.
Let me know if I should send that one, iris$fillInTransparentPixelColors gets mentioned there too.

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.0.0a of Fusion.
Thank you for reporting the issue!
