### ISSUE TITLE
Fusion Dependency 

### ISSUE THREAD

**Issue by Duxtorm** [SuperMartijn642/Rechiseled#37]
Minecraft got mad at me when I tried to launch Rechiseled, saying I needed to install Fusion.. though no word of this dependency was mentioned on the Rechiseled description page.

I'd like only to request that the dependencies for this mod are mentioned in the description.

**Comment by SuperMartijn642** [comment]
CurseForge shows dependencies both under the 'relations' tab:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/a56e93f3-a54c-4fff-9894-dd70bd88ab4f)
And when you click on the file you want to use:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/1a34f6dd-b905-4354-b87b-3eec5e331c49)

Modrinth shows the dependencies when you click on the file you want to use:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/7a1a345d-2606-405a-acdd-c03b81755e04)
