### ISSUE TITLE
[Bug] MC 1.20.1 Exit Code 1

### ISSUE THREAD

**Issue by Devilswarchild** [SuperMartijn642/Rechiseled#38]
**Version Info**
- Minecraft Version: 1.20.1
- Forge Version: 47.0.15
- Re-chiseled Version: rechiseled-1.1.0a-forge-mc1.20.jar

**Description of the Bug**
Exit Code 1 Crash During Boot Up

**Steps to Reproduce**
use my modlist with re-chiseled and the crash will occur/ crash isnt present if re-chiseled is either removed or disabled.

Mods in my modpack:
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Fast Portals (by gluegunner4)](https://www.curseforge.com/minecraft/mc-mods/fast-portals)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Occultism (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/occultism)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[Armourer's Workshop (by RiskyKen)](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop)
[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Erroring Entity Remover Reforged (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/erroring-entity-remover-reforged)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Creeper Firework (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/creeper-firework)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Epic Samurai's (by VeroxUniverse)](https://www.curseforge.com/minecraft/mc-mods/epic-samurais)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[Bigger Stacks (by thanksihadtosignupforthis)](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
[Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/cha-s)
[Lithereal (by TheLightBlueGame)](https://www.curseforge.com/minecraft/mc-mods/lithereal)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[GravelMiner (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/gravelminer)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Variant Crafting Tables [Forge] (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Visual Overhaul (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Chunk Animator (by Lumien231)](https://www.curseforge.com/minecraft/mc-mods/chunk-animator)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)

**Screenshots**

![Screenshot_3](https://github.com/SuperMartijn642/Rechiseled/assets/27385258/19a12b45-11e3-4e8a-a030-b18a7bae96d4)

here are the necessary logs to troubleshooot the error:

[launcher_log.txt](https://github.com/SuperMartijn642/Rechiseled/files/11826557/launcher_log.txt)

[debug.log](https://github.com/SuperMartijn642/Rechiseled/files/11826558/debug.log)

[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/11826559/latest.log)

**Comment by SuperMartijn642** [comment]
The `latest.log` doesn't show any error and appears to be cutoff. Are you sure that's the entire log?

That is quite a lot of mods, please narrow down the mods needed to reproduce the issue.

**Comment by Devilswarchild** [comment]
All i know is that when I turn re-chiseled and its dependency fusion to
disabled the exit code disappears altogether. I also supplied you with a
debug log

**Comment by SuperMartijn642** [comment]
The `debug.log` is pretty much useless unless you have some specific line you're looking for due its size. Apart from that, the `debug.log` also appears to be cutoff similar to the `latest.log`.

That is just too many mods for me to go download 1 by 1. Please narrow down the mods needed to reproduce the issue.

**Comment by Devilswarchild** [comment]
ok I ran it this time with just fusion, re-chiseled , jade and jei

[crash-2023-06-22_20.24.43-client.txt](https://github.com/SuperMartijn642/Rechiseled/files/11842270/crash-2023-06-22_20.24.43-client.txt)
[debug.log](https://github.com/SuperMartijn642/Rechiseled/files/11842271/debug.log)
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/11842272/latest.log)

[launcher_log0.txt](https://github.com/SuperMartijn642/Rechiseled/files/11842273/launcher_log0.txt)

**Comment by PatrickK01** [comment]
Hello, I run as well in this problem.

Installed:
Minecraft 1.20.1
Forge 47.0.34 (also tested with other forge versions)
Fusion 1.0.1
JEI 15.2.0.22
Rechiseled 1.1.0a
SuperMartijn642's Config Library 1.1.6
SuperMartijn642's Core Lib 1.1.9

So just your mod.

Still getting same error as devilswarchild.
Could you please explain, why you closed this Issue unsolved?

Greets

**Comment by SuperMartijn642** [comment]
The issue was a duplicate of one over on Fusion and caused by using a 1.18 version of Fusion on 1.20. I highly doubt your issue is the same, please create a new issue and provide the logs.
