### ISSUE TITLE
[Bug] Minecraft Font Error

### ISSUE THREAD

**Issue by HoneyspringsBw** [SuperMartijn642/Rechiseled#39]
**Version Info**
- Minecraft, 1.19.4
- Rechiseled, 1.1.0a

**Description of the Bug**
All characters of Minecraft's standard font are replaced with Unicode empty boxes that are typically shown when a character is unsupported.

**Steps to Reproduce**
Use Forge mod loader to launch a Modded Minecraft installation in version 1.19.4., hit play in the Minecraft launcher.

**Screenshots**
<img width="1023" alt="Screen Shot 2023-06-24 at 1 16 36 AM" src="https://github.com/SuperMartijn642/Rechiseled/assets/131236073/bab8f0ef-46ba-48cf-8ee4-6639c2d1624a">

**Comment by SuperMartijn642** [comment]
That seems completely unrelated to Rechiseled 🤔

**Comment by HoneyspringsBw** [comment]
> That seems completely unrelated to Rechiseled 🤔

When the mod is removed the error does not occur.

**Comment by SuperMartijn642** [comment]
Everything seems to be fine if I install just Rechiseled and its dependencies. Rechiseled does nothing related to fonts 🤷‍♂️

Are you using other mods? If so, could you narrow down what mods are needed to reproduce the issue?

**Comment by HoneyspringsBw** [comment]
> Everything seems to be fine if I install just Rechiseled and its dependencies. Rechiseled does nothing related to fonts 🤷‍♂️
> 
> Are you using other mods? If so, could you narrow down what mods are needed to reproduce the issue?

It appears to possibly be an issue with optifine and the mod & it's dependencies.

**Comment by SuperMartijn642** [comment]
Ah how surprising, OptiFine manages to break everything. Not much I can do, OptiFine is closed source so I can't know what it does.
Apart from that, Rechiseled has absolutely nothing to do with fonts or font renderering, so I don't know what I'd even fix.

I guess just don't use OptiFine. If you want OptiFine for shaders, you can use Oculus as an alternative.
