### ISSUE TITLE
[Feature] Factory blocks similar to Chisel

### ISSUE THREAD

**Issue by totrider** [SuperMartijn642/Rechiseled#4]
Used the factory themed blocks from chisel extensively in tech build. Blocks like the animated/non animated fans and connected metal structures looked super nice.

**Comment by Nevrai** [comment]
It’s not exactly like the factory blocks from Chisel, but [Builder’s Delight](https://www.curseforge.com/minecraft/mc-mods/builders-delight-forge) has industrial blocks which can be changed to look like fans with animated textures, among other things. I still think it’d be great for Re-chiseled to bring back the factory blocks, though, as well as the [antiblocks](https://ftb.fandom.com/wiki/Antiblock), which were solid-colour blocks not affected by light or shadows.

**Comment by SuperMartijn642** [comment]
I am not copying any textures from Chisel and I will likely not be adding those blocks.

**Comment by totrider** [comment]
Is all good. Today, we have "Factory Blocks" which implements those lovely animated fans https://www.curseforge.com/minecraft/mc-mods/factory-blocks

- for anyone wanting those
