### ISSUE TITLE
Weird incompatibility with Optifine.

### ISSUE THREAD

**Issue by Duxtorm** [SuperMartijn642/Rechiseled#40]
- Minecraft 1.20
- Rechiseled 1.1.0 & 1.1.0a
- Optifine 1.20 HD U I5 pre5

Causes all characters to display as "▯"
https://i.imgur.com/6LE5tHz.png

**Comment by SuperMartijn642** [comment]
Nothing I can do about this. Rechiseled does nothing related to fonts whatsoever 🤷‍♂️ OptiFine is closed source, so I can't know what they are doing.

You can either complain to OptiFine or just use a shader alternative like Oculus or Iris.
