### ISSUE TITLE
[Bug] Chisel GUI does not open when using Ledger

### ISSUE THREAD

**Issue by tronfy** [SuperMartijn642/Rechiseled#41]
**Version Info**
- Minecraft 1.19.2
- Fabric Loader 0.14.21
- Rechiseled 1.1.0b
- Ledger 1.2.5: https://modrinth.com/mod/ledger

**Description of the Bug**
When right-clicking a block with the Chisel item, the Chiseling GUI does not appear. No crashes happen.

An error gets printed to the server logs:
`[Server thread/ERROR]: Failed to handle packet net.minecraft.class_2886@55b5e4f7, suppressing error`
`java.lang.IllegalArgumentException: Invalid hand null`
View log: https://mclo.gs/lyvv05c

This is a similar issue to #32.

**Steps to Reproduce**
Open a Fabric 1.19.2 server with Rechiseled 1.1.0b and Ledger 1.2.5.
Right click any block with a Chisel.

**Comment by SuperMartijn642** [comment]
Should be fixed now in Rechiseled version 1.1.2a for Fabric.
Thank you for reporting the issue!
