### ISSUE TITLE
[Crash] Can't start Minecraft Forge 1.12.2 server with Rechiseled after update, now insists it does not have fusion

### ISSUE THREAD

**Issue by dangerousones** [SuperMartijn642/Rechiseled#43]
**Version Info**
- Minecraft, 1.12.2
- Rechiseled, 1.1.1a

Please see attached images
![image](https://github.com/SuperMartijn642/Rechiseled/assets/23729040/34125e90-bc7b-4cdc-a8dc-98c1ba1d3261)
![image](https://github.com/SuperMartijn642/Rechiseled/assets/23729040/16018805-4098-4b3a-bda2-981547054d38)
![image](https://github.com/SuperMartijn642/Rechiseled/assets/23729040/642fcaf1-d183-4244-8720-11dee15566e3)
(Do note, both Fusion 1.0.0 and 1.0.3 were tested, both result in error)

**Crash report (~/logs/latest.log)**
[crash-2023-07-09_02.32.24-server.txt](https://github.com/SuperMartijn642/Rechiseled/files/11994229/crash-2023-07-09_02.32.24-server.txt)

**Comment by SuperMartijn642** [comment]
From looking at some other 1.12 mods, I found an undocumented `required-after-client` dependency type which seems to fix it.
Should now be fixed in Rechiseled 1.1.1b for Minecraft 1.12.

Thank you for reporting the issue!

**Comment by dangerousones** [comment]
No problem, thank you for fixing it!

**Comment by GameBurrow** [comment]
Same issue on Fabric 1.1.2 MC 1.19.2 version: https://modrinth.com/mod/rechiseled/version/1.1.2-fabric-mc1.19.2
