### ISSUE TITLE
[Bug] [Forge 1.19.2] Rechiseled textures broken with other "fusion" mod installed

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/Rechiseled#44]
**Version Info**
- Minecraft, 1.19.2 (Forge 43.2.10)
- Rechiseled, rechiseled-1.1.1-forge-mc1.19.2

**Description of the Bug**
If [this fusion mod](https://www.curseforge.com/minecraft/mc-mods/fusion) is installed, Rechiseled textures are broken. Additionally, that mod can be installed in place of your fusion mod, and Rechiseled does not complain.

**Steps to Reproduce**
Install rechiseled, your config and core libs, [this fusion mod](https://www.curseforge.com/minecraft/mc-mods/fusion), and it's dependency. You can also install your fusion mod, but this does not seem to affect anything.
Play game.

**Screenshots**
![image](https://github.com/SuperMartijn642/Rechiseled/assets/72479339/76371316-d467-49e1-b039-1cadd707b47d)

**Comment by SuperMartijn642** [comment]
Seems they happen to use the same modid, nothing I can do about that.
