### ISSUE TITLE
[Crash] Crash when launching the game

### ISSUE THREAD

**Issue by sirben99** [SuperMartijn642/Rechiseled#45]
**Version Info**
- Minecraft, 1.16.5
- Rechiseled, 1.1.1

**Steps to Reproduce**
I updated Rechiseled for my modpack and now im getting a crash whenever i launch. Im not getting a crash with version 1.1.0 of Rechiceled, so the newest version has something funny going on presumably.

**Crash report (~/logs/latest.log)**
https://pastebin.com/511KSBxd

**Comment by SuperMartijn642** [comment]
I have fixed it now in version 1.1.2.
Thank you for reporting the issue!
