### ISSUE TITLE
Rechiseled's Cureforge Page does not list it's Required Mod Libraries!!![Bug] ...

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [SuperMartijn642/Rechiseled#46]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled , 1.1.1

**Description of the Bug**
Nowhere on this mod's mod page does it tell you what mods are required to make this mod work.  I had to create a brand new empty instance of Minecraft and load it alone so that forge would tell me what was missing, since if you have too many mods, forge will just quite the game without telling you why.

**Steps to Reproduce**
Load Rechiseled with only Forge and none of it's needed mods.

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
When you click on the file you want to use:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/dbd088cd-c11b-42ae-b978-e55ec503ae56)

When you click on the 'relations' tab:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/2c5bee10-4104-4bae-bb83-8ab722a10a37)

**Comment by 7OOTnegaTerces** [comment]
Uh-uh, not so fast!  That only applies to the "Legacy" version of Curseforge.  Not only is this the OLD way of doing things, and thus likely to be removed at some point in the future, but the new Curseforge, however it may - or may not - work for you, is a much nicer user experience for me, as I can easily see what mods are on what modloaders and even sort files by modloader.  So yeah, you need to support the new Cureforge mod pages, and not just the legacy versions!  ;P

![Rechiseled Download Page](https://github.com/SuperMartijn642/Rechiseled/assets/9096722/40f108bb-886a-48d5-901b-39bd38c369b4)

**Comment by SuperMartijn642** [comment]
If you don't like it, complain to CurseForge. This is the intended way of showing dependencies through CurseForge. They're working on adding the same info to the file tab on the new site.

For now you can just click on the 'relations' tab like I said and like it shows in your screenshot. I am not adding a section to the description because you can't be bothered to go to the dedicated page for it.
