### ISSUE TITLE
[Bug] Texture rendering error 1.16.5 with mod fusion

### ISSUE THREAD

**Issue by Billetiado10** [SuperMartijn642/Rechiseled#47]
**Version Info**
- Minecraft, Version 1.16.5-forge-36.2.39
- Rechiseled, Version rechiseled-1.1.2-forge-mc1.16.jar

**The textures do not appear correctly, I tried disabling CTM optimizers and not interfering with Fusion mod, but the problem persists, UPDATE everything to the latest version.**

**Update the mods
fusion-1.0.3-forge-mc1.16.jar
supermartijn642configlib-1.1.7-forge-mc1.16.jar
supermartijn642corelib-1.1.12-forge-mc1.16.jar**
...
![2023-07-24_22 09 43](https://github.com/SuperMartijn642/Rechiseled/assets/76263374/80775a28-9e79-4648-aba4-b75bc3952c4e)
![2023-07-26_14 11 21](https://github.com/SuperMartijn642/Rechiseled/assets/76263374/699600fd-c3fd-4856-81cc-edb5d6182c27)
![2023-07-26_14 11 30](https://github.com/SuperMartijn642/Rechiseled/assets/76263374/cb362402-35b2-49f5-81a8-7c9bc4404a21)
![2023-07-26_14 11 33](https://github.com/SuperMartijn642/Rechiseled/assets/76263374/ab726f32-91ef-4840-ba01-76a993a9e5b4)

![2023-07-26_14 11 42](https://github.com/SuperMartijn642/Rechiseled/assets/76263374/a36c43f8-bfe5-4a9d-ac88-a9111f7b6820)

**Comment by SuperMartijn642** [comment]
Seems to be working fine with just the files you mentioned:
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/c8e7c53f-1289-4959-965c-7e900ee9e031)

Probably some other mod you have installed that breaks it. Could you narrow down which mods are needed to reproduce the issue?

**Comment by Billetiado10** [comment]
The optimization mods that I have are these:
betterbiomeblend-1.16.4-1.2.9-forge
betterfpsdist-1.2
betterspawnercontrol_1.16.5-3.0
Chunk+Pregenerator-1.16-3.6.4
chunkloaders-1.2.5-forge-mc1.16
connectedglass-1.1.7-forge-mc1.16
crashutilities-3.13
chunksending-1.16.5-2.5
CTM-MC1.16.1-1.1.2.6.jar
dynamiclightsreforged-mc1.16.5_v1.0.1
dynviewdist-2.0
entitycollisionfpsfix-1.16-1.0.1
entityculling-forge-mc1.16.5-1.5.2
ferritecore-2.1.1-forge
fpsreducer-forge-1.24-mc1.16.5
fusion-1.0.3-forge-mc1.16
globaldataandresourcepacks-1.16.5-1.10.2
kryptonreforged-mc1.16.5_v1.0.0
lazydfu-0.1.3
magnesium_extras-mc1.16.5_v1.4.0
memoryleakfix-forge-pre1.17-1.0.0
memorysettings-1.9
modernfix-forge-5.3.2+mc1.16.5
oculus-1.4.5
rechiseled-1.1.2-forge-mc1.16
rubidium-0.2.12
rubidium-extra-0.4.18+mc1.16.5-build.75
saturn-mc1.16.5-0.0.3
smoothboot-forge-1.16.4-1.2.2
spark-1.9.1-forge
TextruesRubidiumOptions-1.0.5-Hotfix-mc1.16.5

Are the ones that modify rendering and such, maybe it's modernfix?
also my modpack has more than 300 mods

**Comment by SuperMartijn642** [comment]
Seems to be a side effect of optimizations by ModernFix which causes Fusion's texture loading to be skipped. I added separate mixins for when ModernFix is installed now in version 1.0.4 of Fusion, similarly to 1.18+.

Thank you for reporting the issue!
