### ISSUE TITLE
[Bug] [1.16.5] Issue with Secret Rooms Mod and Rechiseled

### ISSUE THREAD

**Issue by sirben99** [SuperMartijn642/Rechiseled#48]
**Version Info**
- Minecraft, 1.16.5
- Modloader: Forge
- Rechiseled, 1.1.2
- Secret Rooms Mod: 1.16.5
- Fusion: 1.0.4
- Supermartijn642configlib: 1.1.7
- Supermartijn642corelib: 1.1.11

**Description of the Bug**
Hey!

There seems to be an issue with Secret Rooms Mod (https://www.curseforge.com/minecraft/mc-mods/secretroomsmod) and Rechiseled, where if you place any Secret Rooms Mod block down to a connecting texture Rechiseled block, the secret rooms mod block turns invisible. This does not happen with the normal non-connecting block from Rechiseled.
This might be expected, since i assume its hard to mimic blocks with connecting textures. If this is not a Rechiseled issue, please say so and ill re-direct it!

**Steps to Reproduce**

1. Download Secret Rooms Mod and Rechiceled
2. Create a new singleplayer world
3. Create Connecting blocks with Rechiceled
4. Put any Secret Rooms Mod block on the Rechiseled block
5. Secret Rooms Mod block turns invisible

**Screenshots**
In the screenshot i have a secret trapdoor on a Connecting Rechiseled block on the left, and a secret trap door on a non-connecting Rechiseled block on the right
![2023-07-28_13 07 39](https://github.com/SuperMartijn642/Rechiseled/assets/32977052/61e7ad44-ad29-489f-a277-c2e18e1d6fd8)

**Comment by SuperMartijn642** [comment]
After having a look, this seems to be an issue on Secret Rooms end as the block models from Fusion will always return at least some quads to be rendered. Please report the issue to them.
