### ISSUE TITLE
rechisel for 1.16 will not work for forge version for 1.16

### ISSUE THREAD

**Issue by suneyedset** [SuperMartijn642/Rechiseled#5]
It looks like your file for minecraft 1.16.1 requires a forge version beyond what 1.16 will allow. When downloading the mod, I noticed too that the blurb on the download page says the game version is for 1.18, this happens after definitely clicking on the download link for the earlier version, 1.16.1. No mistake, I clicked on the right link, and did it more than once. The Forge version asked for when trying to play with this is 36 something instead of 32 something. Will not load.

**Comment by SuperMartijn642** [comment]
> It looks like your file for minecraft 1.16.1 requires a forge version beyond what 1.16 will allow.

The latest version for 1.16 is Forge 1.16.5-36.2.34 which works fine with Rechiseled.

> When downloading the mod, I noticed too that the blurb on the download page says the game version is for 1.18, this happens after definitely clicking on the download link for the earlier version, 1.16.1.

Don't know which file you're talking about, they all appear to be marked correctly.
![image](https://user-images.githubusercontent.com/12382965/163676134-79a13731-6729-4467-9652-6bf34deb5863.png)

**Comment by SuperMartijn642** [comment]
Closing due to no response
