### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by 0Crazyy** [SuperMartijn642/Rechiseled#51]
**Version Info**
- Minecraft, 1.18.2
- Rechiseled, 1.1.2

**Steps to Reproduce**
Crashing when adding with ATM 7 To The Sky Modpack

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/12471914/latest.log)

**Comment by SuperMartijn642** [comment]
> Mod §erechiseled§r requires §6fusion§r §o1.0.0 or above§r
§7Currently, §6fusion§r§7 is §o§nnot installed

You'll have to install Fusion as its required for Rechiseled
