### ISSUE TITLE
[Crash] NullPointerException when tesselating block model

### ISSUE THREAD

**Issue by DemonicDemon6** [SuperMartijn642/Rechiseled#52]
**Version Info**
- Minecraft 1.18.2
- Forge 40.2.4
- Rechiseled, 1.1.2

**Description + Reproduce**
Not 100% sure but it has something to do with rendering connected textures. It tries to check if a list is empty (check the crash report below) but it throws a null. Each time, it is a different block that causes the crash and there isn't any sort of pattern.

**Crash report (~/logs/latest.log)**
[crash-2023-09-11_22.11.29-client.txt](https://github.com/SuperMartijn642/Rechiseled/files/12580530/crash-2023-09-11_22.11.29-client.txt)

**Comment by SuperMartijn642** [comment]
Looking at the code, it should be impossible for Fusion's connecting block model to ever return null, so I would have to assume it is some other mod messing with it.
I tried to reproduce the issue with the same mods you have installed in the crash log, but everything seemed to work fine.
Does the crash occur consistently?

Also, could you provide the latest.log file as well? Not completely sure if that will help, but it sometimes shows some errors which occurred ealier.

**Comment by DemonicDemon6** [comment]
It happens at least once a day (assuming I go on the server). When I rejoin, it sometimes crashes again after a few seconds but usually it will be fine. Some of the other people on the server have experienced the same crash before but less frequently (as their bases don't have as many connecting rechiseled blocks).

Now that I think about it, could it have anything to do with the Create mod moving the blocks? Anyways, here is the latest.log file (in this, I crashed 3 seconds after joining the server)
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/12590480/latest.log)

**Comment by SuperMartijn642** [comment]
I tried once more to reproduce the issue by creating a flat world made of just the pulverized cobblestone block and flying around for a bit, but I still wasn't able to reproduce the crash.

After looking at the code again, I have one small adjustment which potentially could have something to do with it although I kinda doubt it. Could you maybe try out this jar: https://uploadnow.io/f/YmS8tlm. It has the same version number as the current latest release for Fusion, so you should have no trouble joining the server with it.

If that doesn't work, I really have no clue sadly.

**Comment by SuperMartijn642** [comment]
Have you had any chance to try out the jar file I shared?

**Comment by DemonicDemon6** [comment]
The fix worked! I have not received another crash after using it, though it might be a coincidence as I changed some of my graphics settings on the Nvidia control panel around the same time (for different reasons), but at least I can play now lol. 

Thanks for the help! I really appreciate it :D

**Comment by SuperMartijn642** [comment]
The crash is purely Java logic, so Nvidia graphics settings *shouldn't* affect it. I have released the changes as Fusion 1.0.6 now. In case you still encounter crashes, let me know.
Thank you for reporting the issue!
