### ISSUE TITLE
[Crash] Rechiseled or fusion

### ISSUE THREAD

**Issue by ferreiraalex** [SuperMartijn642/Rechiseled#54]
**Version Info**
- Minecraft, ...
- Rechiseled, ...

**Steps to Reproduce**
...
[crash-2023-09-14_20.01.53-client.txt](https://github.com/SuperMartijn642/Rechiseled/files/12611572/crash-2023-09-14_20.01.53-client.txt)
[crash-2023-09-14_19.54.20-client.txt](https://github.com/SuperMartijn642/Rechiseled/files/12611573/crash-2023-09-14_19.54.20-client.txt)

**Crash report (~/logs/latest.log)**
...

**Comment by ferreiraalex** [comment]
All info in crash report

**Comment by SuperMartijn642** [comment]
Please fill in the template.

When does this crash occur?
You are using a lot of mods, please narrow down the mods needed to reproduce the issue.
