### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Th4V7** [SuperMartijn642/Rechiseled#56]
**Version Info**
- Minecraft, 1.20
- Rechiseled, 1.1.4

**Description of the Bug**
... Chiseled Copper Blocks do not break faster with a pickaxe and never drop themselves.

**Steps to Reproduce**
... Place any of the rechiseled copper block variants and break them

**Screenshots**
...

**Comment by Th4V7** [comment]
Looking at the code, copper variants seem to have a unique definition as opposed to pulling from the vanilla block

**Comment by SuperMartijn642** [comment]
> Looking at the code, copper variants seem to have a unique definition as opposed to pulling from the vanilla block

That is intentional as Create's oxidation stuff causes a crash when the copper block is loaded early.

I added the copper blocks to the appropriate tags now in Rechiseled version 1.0.4a, so it should all be mineable now.
Thank you for reporting the issue!
