### ISSUE TITLE
[Crash] ...[1.18.2] forgeError: java.lang.IllegalStateException: Render layers can only be set during client loading! This might ideally be done from `FMLClientSetupEvent`

### ISSUE THREAD

**Issue by SDUBZ** [SuperMartijn642/Rechiseled#6]
**Version Info**
- Minecraft, 1.18.2
- Wireless Chargers, wirelesschargers-1.0.6-forge-mc1.18
- rechisel:rechiseled-1.0.10a-mc1.18
- forge: 1.18.2-40.1.51

**Steps to Reproduce**
load up game with mods liste
wait for it to hit the main menu 
get crash

**Crash report (~/logs/latest.log)**
...
[crash-2022-06-10_15.28.21-client.txt](https://github.com/SuperMartijn642/Rechiseled/files/8876043/crash-2022-06-10_15.28.21-client.txt)
[debug.log](https://github.com/SuperMartijn642/Rechiseled/files/8876046/debug.log)
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/8876047/latest.log)

**Comment by SuperMartijn642** [comment]
This is caused by a change introduced in Forge 40.1.43. Probably an easy fix when I have some time.

For now, downgrading to Forge 40.1.42 would be a temporary solution.

**Comment by SDUBZ** [comment]
i cant do that because another mod requires higher then 48

**Comment by SuperMartijn642** [comment]
Looking at the log now, the crash is caused by ConnectedTexturesMod or Chisel and has nothing to do with Rechiseled.
Please report the issue to them.
