### ISSUE TITLE
[Bug] Wrong red nether bricks names

### ISSUE THREAD

**Issue by unroman** [SuperMartijn642/Rechiseled#60]
**Version Info**
- Rechiseled

**Description of the Bug**
Wrong block names. Blocks made from red nether bricks don't have "red" in their names

**Screenshots**
![image](https://github.com/SuperMartijn642/Rechiseled/assets/75941881/3502591d-5279-48b0-b8f7-c7117feb939a)

**Comment by SuperMartijn642** [comment]
I fixed it now in Rechiseled version 1.1.5.
Thank you for reporting the issue!
