### ISSUE TITLE
[Bug] Rechiseled copper blocks aren't breackable

### ISSUE THREAD

**Issue by JackYevhen** [SuperMartijn642/Rechiseled#62]
**Version Info**
- Minecraft, 1.20.2
- Rechiseled, 1.1.4

**Description of the Bug**
Mining level of (even nethrite) pickaxe isn't strong enough for rechiseled copper blocks. (The breach extremely slow like stone with hand, and don't drop)

**Steps to Reproduce**
Boot Minecraft 1.20.2 (maybe any 1.20 I heven't checked).
Create a world.
Mine 9 copper and 1 iron.
Smelt the ores.
Craft a block of copper and a chisel.
Rechisel ot to anything except the original one.
Place it.
Give your-self any pick you want.
Try breaking it.
Spent a lot of time doing it.
Get nothing dropped.

**Screenshots**
<img width="1792" alt="Screenshot 2023-10-29 at 08 26 38" src="https://github.com/SuperMartijn642/Rechiseled/assets/96749330/22e84d34-6a76-4656-919e-bee8b5171c55">
*[Takes to much time]*

<img width="1792" alt="Screenshot 2023-10-29 at 08 26 48" src="https://github.com/SuperMartijn642/Rechiseled/assets/96749330/c244a3da-b25e-462b-beeb-ebe7b8bdf188">
*No Item Drops*

**Comment by SuperMartijn642** [comment]
This has already been fixed, please update to a newer version.

**Comment by JackYevhen** [comment]
thanks
