### ISSUE TITLE
[Crash] When breaking rechiseled blocks

### ISSUE THREAD

**Issue by aqua-air** [SuperMartijn642/Rechiseled#66]
Sanctum Network Modpack latest version (5.55) and operating on forge 47.2.5 (latest)
rechiseled 1.1.5.b.forge

So when you try to break rechiseled blocks you will just crash, and anyone nearby rendering the block also crashes. 
This does NOT happen in creative mode. 
Which makes me think it's an issue rendering the block-breaking animation. 
I can confirm this happens with acacia plank bricks, pulverized cobblestone, and likely more. 

[THIS is the crash report](https://mclo.gs/qXjeEGe)

**Comment by NateT27** [comment]
same here except
 i have the stone path crashing

**Comment by SuperMartijn642** [comment]
Fixed now in Fusion version 1.1.0a.
Thank you for reporting the issue!
