### ISSUE TITLE
[Bug] Mining a connected texture block crashes Minecraft

### ISSUE THREAD

**Issue by DarkPhoenixCoding** [SuperMartijn642/Rechiseled#69]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.5b
- Fusion, 1.1.0

**What mod loader are you using?**: Forge

**Description of the Bug**
Connected textures cause crash when mining in survival

**Steps to Reproduce**
1. Create custom profile in Curseforge with Rechiseled and its dependencies
2. Use a chisel and any block to create a rechiseled block (with connected textures enabled)
3. Mine the block in survival (game crashes)

**Comment by SuperMartijn642** [comment]
This has been fixed in Fusion 1.1.0a. Please update Fusion.

**Comment by DarkPhoenixCoding** [comment]
That's how I did it initially, but then the game reports back that fusion is not installed when it 100% is. If I downgrade Fusion I don't get this error.

Mod *rechiseled* requires *fusion* _1.0.0 or above_
Currently, *fusion* is _not installed_

**Comment by SuperMartijn642** [comment]
Are you sure you downloaded the Forge version and not the Fabric one?

**Comment by DarkPhoenixCoding** [comment]
I'm using Curseforge launcher if that changes anything?

![fusion broken or something](https://github.com/SuperMartijn642/Rechiseled/assets/26417642/4202c335-ba9d-45d4-8eba-f94a3216665f)

**Comment by SuperMartijn642** [comment]
The CurseForge launcher has a bug where it sometimes doesn't downloaded the files correctly and they won't get loaded by Forge. Can you try deleting the file currently in the mods folder and downloading it manually from the site?

**Comment by DarkPhoenixCoding** [comment]
I'll try it and report back with my findings

**Comment by DarkPhoenixCoding** [comment]
Yep, that was it. Thanks for the help! Very strange that that occurred as it did. I was really disappointed when my game crashed using this mod in my own mod pack because I really like it, but now I get to use it without problem!
