### ISSUE TITLE
[Crash] Block Render

### ISSUE THREAD

**Issue by CoNnEcT500BR** [SuperMartijn642/Rechiseled#71]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, v1.15b
- Fusion, v1.1.0

**What mod loader are you using?**: Forge

**Steps to Reproduce**
Just create the "bordered cobblestone" block with the textures connected (at least that's how I tested it), place the block on the ground and then try to break it, specifically in survival mode, when trying to render the texture of the block breaking it crashes Minecraft

**Crash report (~/logs/latest.log)**
[https://pastebin.pl/view/0e7e0b37](url)

**Comment by SuperMartijn642** [comment]
This has been fixed in Fusion 1.1.0a. Your comment says you are using `Fusion, v1.10a`, but the log you shared shows Fusion 1.1.0.

**Comment by CoNnEcT500BR** [comment]
> This has been fixed in Fusion 1.1.0a. Your comment says you are using `Fusion, v1.10a`, but the log you shared shows Fusion 1.1.0.

ohh, sorry mate, I was looking at the versions and I accidentally put version 1.1.0a, but in fact it's version 1.1.0

**Comment by CoNnEcT500BR** [comment]
I tested it with version 1.1.0a and it worked without a problem, thank you.
