### ISSUE TITLE
Please Properly Label Mods

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SuperMartijn642/Rechiseled#72]
https://dl.dropboxusercontent.com/scl/fi/tmeabolavh564z184bzo1/Discord_QuTRgDsbrv.png?rlkey=fiwmcaxq39vo7vtmjfjcm45hf&dl=0

``The NeoForged Project #announcements
SERVER
 — 11/13/2023 9:21 AM
Public Service Announcement 📣
CurseForge have notified us that a number of mods currently have releases for 1.20.2 that are marked both Forge and NeoForge which are causing issues for end users.

This is a good chance to remind modders that Forge and NeoForge are no longer compatible in 1.20.2.

Please remember to tag your 1.20.2 and newer files for the loaders the mod has been tested to work on.``

**Comment by SuperMartijn642** [comment]
As it is one file for 1.20.1 and 1.20.2, there is no way for me to mark it correctly as it works on Forge 1.20.1 & 1.20.2 and NeoForge 1.20.1.
I can't select the Minecraft versions per loader, so it is either 1.20.2 for both or for neither.

**Comment by P3rf3ctXZer0** [comment]
You could take a page from Serilum ... they worked around it by using folder callbacks and now they have fabric forge and neo on the same mod ... Not sure how hard it is but the alternative is just seperate projects. I am not sure what you exactly need to do and I don't code I was just relaying information. Love your work especially entangled and packed up :)
