### ISSUE TITLE
[Bug] Unable to select connected textures on some blocks and weird visual bugs

### ISSUE THREAD

**Issue by franmatesic** [SuperMartijn642/Rechiseled#73]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.1.5b
- Fusion, 1.1.0a

**What mod loader are you using?**: Forge

**Description of the Bug**
Option for connected texture missing disabled on first 7 blocks and enabled on other blocks. 
These first 7 blocks cannot be chiseled connected.
Choosing connected texture on a block makes a weird visual where only first 7 blocks are visible, but disabled, and no preview is visible, even though the block can be chiseled with a connected texture.

**Steps to Reproduce**
Try chiseling a block on the right versions.

**Screenshots**

Weird visual when selecting connected texture and no preview visible

![2023-11-16_13 38 40](https://github.com/SuperMartijn642/Rechiseled/assets/25988237/5831a179-97cc-4982-95c4-ece20e46fcd5)

Cannot select connected texture for the first 7 blocks

![2023-11-16_13 38 49](https://github.com/SuperMartijn642/Rechiseled/assets/25988237/d3af038e-1187-47e7-8d55-293314b7e2e1)

Can select connected texture for other blocks

![2023-11-16_13 38 37](https://github.com/SuperMartijn642/Rechiseled/assets/25988237/a525d256-66cd-4da0-9d46-c7b9f93b839b)

**Comment by SuperMartijn642** [comment]
The blocks being invisible is fixed now in version 1.1.5c for Forge 1.19 - 1.20.

> Cannot select connected texture for the first 7 blocks

As for those first 7 blocks, those simply don't have connected variants.

Thank you for reporting the issue!
