### ISSUE TITLE
[Feature] Developer Textures/Programmer Art Support

### ISSUE THREAD

**Issue by kinker31** [SuperMartijn642/Rechiseled#76]
## Is Your Feature Request Related to a Problem?
Technically not, but I do run Minecraft with a resource pack or two that reverts the artstyle it's pre-1.13 look, even with blocks added after. 

## Describe Solution
An extra resource pack could be included with the mod, that replaces the textures of the blocks with their Programmer Art equivalents, or the best interpretation to that look.

**Comment by SuperMartijn642** [comment]
This would basically double my work for Rechiseled as I would have to make two versions of every texture. As I don't think many people would even use it, I don't think it is worth that kind of effort.
This is something that can also easily be done using a separate resource pack not necessarily included in Rechiseled.
I won't be doing this, thank you for the suggestion though!
