### ISSUE TITLE
[Bug] Blocks with wrong textures

### ISSUE THREAD

**Issue by Sabotake** [SuperMartijn642/Rechiseled#78]
**1.18.2**
- Minecraft, a little bit modded like Life in the Woods with 30 mods
- Rechiseled, 1.1.5b
- Fusion, 4.1.2.0

**What mod loader are you using?**: Forge

**Description of the Bug**
The textures from the blocks don't load correctly, some do but the most don't

**Steps to Reproduce**
Just installed it and created a new world

**Screenshots**
![bug](https://github.com/SuperMartijn642/Rechiseled/assets/152808996/b13e08c0-e937-4c7a-8815-0036bed97c72)
![bug 2](https://github.com/SuperMartijn642/Rechiseled/assets/152808996/d76864d8-3158-4103-845e-c0cc4b1949fd)

**Comment by SuperMartijn642** [comment]
> Fusion, 4.1.2.0

That is not a version of Fusion 🤔
Are you sure you have the right mod? This one https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

**Comment by Sabotake** [comment]
Ahh ok I downloaded the wrong Fusion.

That's what I downloaded https://www.curseforge.com/minecraft/mc-mods/fusion. Now it works fine XD

Thx

**Comment by MusicallyInspired** [comment]
I hate to reopen this issue, but what if we wanted both Fusion and SimpleOres' Fusion at the same time? I've been wondering why my textures looked horribly mangled in this mod like the above example for a while now. Now I see it's an incompatibility with the other mod named Fusion (the same one Sabotake linked to). I have the proper Fusion installed and my textures are still garbage. Is it really necessary to remove the SimpleOres Fusion mod to make this work? Can anything be done about it? If not I understand.

My setup
MC Version: 1.19.2
Forge Version: 43.2.14
Rechiseled Version: 1.1.5c
Fusion Version: 1.1.0b

**Comment by SuperMartijn642** [comment]
@MusicallyInspired you can see https://github.com/SuperMartijn642/Fusion/issues/36 for a explanation of why the mods conflict.
This is not something which can easily be fixed as changing the modid for an already released mod causes all kinds of issues.
