### ISSUE TITLE
[Bug] neoforge networking

### ISSUE THREAD

**Issue by kittech0** [SuperMartijn642/Rechiseled#83]
**Describe the bug**
Not compatible with latest neoforge version (20.4.142-beta) with networking

**Screenshots**
![obraz](https://github.com/Nyphet/harvest-with-ease/assets/73485099/7f59bf71-bdf0-470f-8689-ef2e216271cc)

**Stacktrace and logs**
https://gist.github.com/NeoCamelot/6b30b7fb7861991ac0eadbcafb0a3ed3

**Comment by SuperMartijn642** [comment]
NeoForge 20.4.70-beta had breaking changes where they removed a bunch of networking stuff used by my mods. I have now updated both my core and config library to account for the changes. Installing the new updates should fix the issue.
Thank you for reporting the issue!
