### ISSUE TITLE
[Crash] Cannot start the game 

### ISSUE THREAD

**Issue by TobiasReindl** [SuperMartijn642/Rechiseled#84]
**Version Info**
- Minecraft, 1.20.4
- Rechiseled, 1.1.5b
- Fusion, 1.1.0d

**What mod loader are you using?**: Fabric

**Steps to Reproduce**
This is the same issue as the one for Fusion, but I thought I try to post this twice so maybe anyone will see this:
https://github.com/SuperMartijn642/Fusion/issues/44
Was using Continuity for connected textures before and want to add Rechiseled so I also had to download Fusion.
Wanted to open up the game and it crashes. I also tried to disable the "Eating Animations Mod". 
Dont really know what else I can do now. Also tried to disable Rechiseled so that I only launch it with Fusion. Same crash there so it also has to do something with Fusion (I guess).

**Crash report (~/logs/latest.log)**

First:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'eatinganimationid'!"

After disabling Eating Animations:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.resource.loader.ModNioResourcePack failed"

**Comment by SuperMartijn642** [comment]
Ah this issue has been fixed already, just forgot to close the issue I guess.
Thank you for reporting the issue!
