### ISSUE TITLE
[Bug] Broken and undefined textures.

### ISSUE THREAD

**Issue by AngelPalomar** [SuperMartijn642/Rechiseled#89]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.1.6
- Fusion, 5.1.2.2

**What mod loader are you using?**: Forge 43.3.0

**Description of the Bug**
Most of the rechiseled textures show an error displaying the texture in the block, and the connected textures ones have the undefined texture of Minecraft; after placing one of the undefined blocks, the game crashes.

**Steps to Reproduce**
Install the mentioned versions of the Rechiseled, Rechiseled: Create, Fusion and the required libs, create a world, create the chisel.

**Screenshots**
![2024-05-06_13 40 47](https://github.com/SuperMartijn642/Rechiseled/assets/60854322/364e5af4-6a9c-4cf0-9325-2ef09d828250)
![2024-05-06_13 46 01](https://github.com/SuperMartijn642/Rechiseled/assets/60854322/0f663545-1a45-48e9-8098-b76cd4b21c76)
![2024-05-06_13 46 15](https://github.com/SuperMartijn642/Rechiseled/assets/60854322/30a660f1-d527-4131-bc83-d676544e79f9)

**Comment by SuperMartijn642** [comment]
> - Fusion, 5.1.2.2

I think you installed the wrong Fusion mod, as that is not a version of Fusion. You need to install this one https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures. You should remove the other Fusion mod, otherwise the correct Fusion won't load.

**Comment by AngelPalomar** [comment]
Oh my bad, well I removed that strange Fusion mod and now its fixed, sorry! )':
