### ISSUE TITLE
[Bug] Connected textures incompatibility with Sodium

### ISSUE THREAD

**Issue by CrackedEmerald** [SuperMartijn642/Rechiseled#92]
**Version Info**
- Minecraft: 1.20.1
- Rechiseled: 1.1.6
- Fusion: 1.1.1

**Fabric Modloader**

**Description of the Bug**

Connected textures not connecting, they look like their non connecting versions, making the two blocks identical

**Steps to Reproduce**

Place blocks with connected textures
Enable Sodium (0.5.8+mc1.20.1)
Connected textures not working with Sodium enabled.

**Screenshots**

Sodium off
![2024-06-01_20 18 23](https://github.com/SuperMartijn642/Rechiseled/assets/99568170/020a705a-7b25-43fd-93ea-12e92cc8b53b)

Sodium on
![2024-06-01_20 23 42](https://github.com/SuperMartijn642/Rechiseled/assets/99568170/367787f9-0d2c-40c1-b7f0-2a537d087bc1)

**Comment by SuperMartijn642** [comment]
If you are using Sodium, you will also have to install [Indium](https://www.curseforge.com/minecraft/mc-mods/indium). Sodium replaces the vanilla renderer with one which ignores the Fabric Rendering API. This means any mod which uses the Fabric Rendering API is broken by Sodium. Indium patches Sodium to support the Fabric Rendering API.
