### ISSUE TITLE
[Feature] New Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [SuperMartijn642/Rechiseled#96]
I would love it if each group of chiselled blocks (dirt, cobble, etc) had specific tags, like Rechiseled:dirt for example. This would make things way easier!

**Comment by SuperMartijn642** [comment]
What would your usecase for such tags be?

**Comment by TheBedrockMaster** [comment]
> What would your usecase for such tags be?

Kind of a weird one,
I was going to add EMC to some of these blocks for ATM9sky but without tags it would take...a while.
