### ISSUE TITLE
[Feature] Add Dirt to the Dirt Tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [SuperMartijn642/Rechiseled#98]
**Describe the solution you'd like**

Add Dirt from this mod to the `minecraft:dirt` item tag, so it works in recipes that require dirt.

**Comment by SuperMartijn642** [comment]
My reason for not adding all of the dirt variants to the dirt tag (or any of the other block variants to respective tags) is that it is often annoying when recipes in recipe viewer mods like JEI/REI/EMI show a bunch of seemingly random blocks in recipes when the actual input is just simply dirt.
As the blocks from Rechiseled are just meant for decorative purposes, I think not being able to craft with them is far less of an annoyance then them cluttering a bunch of recipes.

**Comment by TheBedrockMaster** [comment]
That's a fair point, that often is annoying, but as a QoL feature, giving them their own tag (`rechieseled:dirt`, for example) would be very useful for if a pack wanted to use them for something.
